CREATE DATABASE GM;
USE GM;

-- 1. SUPPLIER  TABLE
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);
SELECT * FROM supplier;

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);
SELECT * FROM categories;

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);
SELECT * FROM employees;

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);
SELECT * FROM customers;

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
SELECT * FROM products;

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
SELECT * FROM orders;

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);
SELECT * FROM order_details;

-- CUSTOMER INSIGHTS
-- 1. How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS unique_customers
FROM orders;

-- 2. Customers with the highest number of orders
SELECT 
    c.cust_name,
    COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY c.cust_name
ORDER BY total_orders DESC;

-- 3. Total & Average purchase value per customer
SELECT 
    c.cust_name,
    SUM(od.total_price) AS total_purchase,
    AVG(od.total_price) AS avg_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_name;

-- 4. Top 5 customers by total purchase amount
SELECT 
    c.cust_name,
    SUM(od.total_price) AS total_spent
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_name
ORDER BY total_spent DESC
LIMIT 5;

-- 2️.Product Performance

-- 1. Number of products in each category
SELECT 
    cat.cat_name,
    COUNT(p.prod_id) AS product_count
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name;

-- 2. Average price of products by category
SELECT 
    cat.cat_name,
    ROUND(AVG(p.price),2) AS avg_price
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name;

-- 3. Products with highest sales volume (quantity)
SELECT 
    p.prod_name,
    SUM(od.quantity) AS total_quantity_sold
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_quantity_sold DESC;

-- 4. Total revenue generated by each product
SELECT 
    p.prod_name,
    SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_revenue DESC;

-- 5. Product sales by category & supplier
SELECT 
    cat.cat_name,
    s.sup_name,
    SUM(od.total_price) AS revenue
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN categories cat ON p.cat_id = cat.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY cat.cat_name, s.sup_name
ORDER BY revenue DESC;

-- 3️.Sales & Order Trends

-- 1. Total number of orders
SELECT COUNT(*) AS total_orders
FROM orders;

-- 2. Average order value
SELECT 
    ROUND(AVG(order_total),2) AS avg_order_value
FROM (
    SELECT ord_id, SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) t;

-- 3. Dates with most orders
SELECT 
    order_date,
    COUNT(ord_id) AS order_count
FROM orders
GROUP BY order_date
ORDER BY order_count DESC;

-- 4. Monthly order & revenue trends
SELECT 
    SUBSTRING(order_date,1,7) AS month,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    SUM(od.total_price) AS revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month;

-- 5. Weekday vs Weekend order patterns
SELECT 
    CASE 
        WHEN DAYOFWEEK(order_date) IN (1,7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(ord_id) AS total_orders
FROM orders
GROUP BY day_type;

-- 4.Supplier Contribution

-- 1. Total suppliers
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- 2. Supplier providing most products
SELECT 
    s.sup_name,
    COUNT(p.prod_id) AS product_count
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name
ORDER BY product_count DESC;

-- 3. Average product price per supplier
SELECT 
    s.sup_name,
    ROUND(AVG(p.price),2) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name;

-- 4. Supplier contribution by revenue
SELECT 
    s.sup_name,
    SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_name
ORDER BY total_revenue DESC;

-- 5.Employee Performance

-- 1.Employees who processed orders
SELECT COUNT(DISTINCT emp_id) AS active_employees
FROM orders;

-- 2. Employees handling most orders
SELECT 
    e.emp_name,
    COUNT(o.ord_id) AS orders_handled
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_name
ORDER BY orders_handled DESC;

-- 3. Total sales value handled by each employee
SELECT 
    e.emp_name,
    SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_name;

-- 4. Average order value per employee
SELECT 
    e.emp_name,
    ROUND(AVG(order_total),2) AS avg_order_value
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN (
    SELECT ord_id, SUM(total_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) t ON o.ord_id = t.ord_id
GROUP BY e.emp_name;

-- 6.Order Details – Deep Dive 

-- 1. Quantity vs total price
SELECT quantity, total_price
FROM order_details;

-- 2. Average quantity ordered per product
SELECT 
    p.prod_name,
    ROUND(AVG(od.quantity),2) AS avg_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name;

-- 3. Unit price variation across orders
SELECT 
    prod_id,
    MIN(each_price) AS min_price,
    MAX(each_price) AS max_price
FROM order_details
GROUP BY prod_id;

